inherit_from:
  - ../ruby.yml

Lint/UnusedBlockArgument:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  ()
    '%i': '[]'
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '[]'
    '%W': '[]'
    '%x': ()
  Enabled: true

LineLength:
  Max: 120

Rails/Validation:
  Enabled: false
